version: '3'
services:
  db:
    ports:
      - "5432:5432"
    image: postgres
    environment:
      POSTGRES_DB: 'users-app'
      POSTGRES_USER: 'users-app'
      POSTGRES_PASSWORD: 'users-app'

  backend:
    depends_on:
      - db
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    command: "yarn start"
    volumes:
      - "./backend/users-app:/users-app"
    ports:
      - "1488:3000"
    links:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: "yarn start"
    volumes:
      - "./frontend/users-app/src:/frontend/src"
    ports:
      - 3000:3000
      - 80:80
